import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Trash2, FileText, Sparkles, Edit, X } from 'lucide-react';
import { templateService } from '../services/dataService';
import { aiService } from '../services/aiService';
import { Button, Input, Modal, Loader } from '../components/UI/UI';
import toast from 'react-hot-toast';
import './Templates.css';

const categories = ['business', 'personal', 'marketing', 'support', 'other'];

const Templates = () => {
  const [templates, setTemplates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isAIModalOpen, setIsAIModalOpen] = useState(false);
  const [currentTemplate, setCurrentTemplate] = useState(null);
  
  const [formData, setFormData] = useState({
    name: '', subject: '', body: '', category: 'other',
  });
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiCategory, setAiCategory] = useState('business');
  const [aiGenerating, setAiGenerating] = useState(false);

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    try {
      setLoading(true);
      const res = await templateService.getAll();
      setTemplates(res.data);
    } catch {
      toast.error('Failed to load templates');
    } finally {
      setLoading(false);
    }
  };

  const handleOpenCreate = () => {
    setCurrentTemplate(null);
    setFormData({ name: '', subject: '', body: '', category: 'other' });
    setIsModalOpen(true);
  };

  const handleOpenEdit = (template) => {
    setCurrentTemplate(template);
    setFormData({
      name: template.name,
      subject: template.subject || '',
      body: template.body,
      category: template.category || 'other',
    });
    setIsModalOpen(true);
  };

  const handleSave = async (e) => {
    e.preventDefault();
    if (!formData.name.trim() || !formData.body.trim()) {
      toast.error('Name and Body are required');
      return;
    }

    try {
      if (currentTemplate) {
        const res = await templateService.update(currentTemplate._id, formData);
        setTemplates((prev) =>
          prev.map((t) => (t._id === currentTemplate._id ? res.data : t))
        );
        toast.success('Template updated');
      } else {
        const res = await templateService.create(formData);
        setTemplates((prev) => [res.data, ...prev]);
        toast.success('Template created');
      }
      setIsModalOpen(false);
    } catch {
      toast.error('Failed to save template');
    }
  };

  const handleDelete = async (id, e) => {
    e.stopPropagation();
    try {
      await templateService.delete(id);
      setTemplates((prev) => prev.filter((t) => t._id !== id));
      toast.success('Template deleted');
    } catch {
      toast.error('Failed to delete template');
    }
  };

  const handleAIGenerate = async () => {
    if (!aiPrompt.trim()) return;
    setAiGenerating(true);
    try {
      const res = await aiService.generateTemplate({
        description: aiPrompt,
        category: aiCategory,
      });
      
      // Load generated content into main form data and open standard compose modal
      setFormData({
        name: res.data.name || 'AI Generated Template',
        subject: res.data.subject || '',
        body: res.data.body || '',
        category: aiCategory,
      });
      setCurrentTemplate(null);
      setIsAIModalOpen(false);
      setIsModalOpen(true);
      toast.success('Template generated by AI!');
    } catch {
      toast.error('Failed to generate template');
    } finally {
      setAiGenerating(false);
    }
  };

  return (
    <div className="templates-page">
      <div className="templates-header">
        <div>
          <h1>Email Templates</h1>
          <p>Create and manage reusable email templates</p>
        </div>
        <div className="templates-actions">
          <Button
            variant="secondary"
            icon={<Sparkles size={16} />}
            onClick={() => setIsAIModalOpen(true)}
          >
            AI Generate
          </Button>
          <Button
            variant="primary"
            icon={<Plus size={16} />}
            onClick={handleOpenCreate}
          >
            New Template
          </Button>
        </div>
      </div>

      {loading ? (
        <Loader size="lg" text="Loading templates..." />
      ) : templates.length === 0 ? (
        <div className="templates-empty-state">
          <FileText size={48} className="templates-empty-icon" />
          <h3>No Templates</h3>
          <p>Create templates to write emails faster.</p>
        </div>
      ) : (
        <div className="templates-grid">
          {templates.map((template) => (
            <motion.div
              key={template._id}
              className="template-card"
              whileHover={{ y: -4 }}
              onClick={() => handleOpenEdit(template)}
            >
              <div className="template-card-header">
                <span className="template-category-badge">{template.category}</span>
                {template.isAIGenerated && (
                  <span className="template-ai-badge">
                    <Sparkles size={12} /> AI
                  </span>
                )}
                <button
                  className="template-delete-btn"
                  onClick={(e) => handleDelete(template._id, e)}
                >
                  <Trash2 size={14} />
                </button>
              </div>
              <h3 className="template-card-title">{template.name}</h3>
              {template.subject && (
                <p className="template-card-subject">
                  <strong>Subject:</strong> {template.subject}
                </p>
              )}
              <div className="template-card-preview">
                {template.body.replace(/<[^>]*>/g, '').substring(0, 120)}...
              </div>
            </motion.div>
          ))}
        </div>
      )}

      {/* Manual Create / Edit Modal */}
      <Modal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        title={currentTemplate ? 'Edit Template' : 'New Template'}
        size="lg"
      >
        <form onSubmit={handleSave} className="template-form">
          <Input
            label="Template Name"
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            placeholder="e.g. Follow up email"
            required
          />
          
          <div className="input-group">
            <label className="input-label">Category</label>
            <select
              value={formData.category}
              onChange={(e) => setFormData({ ...formData, category: e.target.value })}
              className="template-select"
            >
              {categories.map((c) => (
                <option key={c} value={c}>
                  {c.charAt(0).toUpperCase() + c.slice(1)}
                </option>
              ))}
            </select>
          </div>

          <Input
            label="Email Subject"
            value={formData.subject}
            onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
            placeholder="Subject line (supports [PLACEHOLDER] markers)"
          />

          <div className="input-group">
            <label className="input-label">Email Body</label>
            <textarea
              value={formData.body}
              onChange={(e) => setFormData({ ...formData, body: e.target.value })}
              placeholder="Write your template text here..."
              rows={8}
              required
              className="template-textarea"
            />
          </div>

          <div className="template-modal-footer">
            <Button variant="ghost" type="button" onClick={() => setIsModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="primary" type="submit">
              {currentTemplate ? 'Save Changes' : 'Create Template'}
            </Button>
          </div>
        </form>
      </Modal>

      {/* AI Generator Modal */}
      <Modal
        isOpen={isAIModalOpen}
        onClose={() => setIsAIModalOpen(false)}
        title="Generate Template with AI"
        size="md"
      >
        <div className="template-ai-form">
          <div className="input-group">
            <label className="input-label">Describe your template needs</label>
            <textarea
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              placeholder="e.g., 'A professional cold outreach email to invite someone to join our beta program'"
              rows={4}
              className="template-textarea"
            />
          </div>

          <div className="input-group">
            <label className="input-label">Category</label>
            <select
              value={aiCategory}
              onChange={(e) => setAiCategory(e.target.value)}
              className="template-select"
            >
              {categories.map((c) => (
                <option key={c} value={c}>
                  {c.charAt(0).toUpperCase() + c.slice(1)}
                </option>
              ))}
            </select>
          </div>

          <div className="template-modal-footer">
            <Button variant="ghost" type="button" onClick={() => setIsAIModalOpen(false)}>
              Cancel
            </Button>
            <Button
              variant="primary"
              onClick={handleAIGenerate}
              loading={aiGenerating}
              icon={<Sparkles size={14} />}
            >
              Generate Template
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default Templates;
